name: Deploy Book
on:
  push:
    branches:
      - main
jobs:
  pages:
    name: GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          
      - uses: Swatinem/rust-cache@v1

      - name: Install mdBook
        run: (test -x $HOME/.cargo/bin/mdbook || cargo install mdbook --no-default-features --features search)

      - name: Build mdBook
        run: mdbook build

      - name: Deploy to GitHub
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: book
