name: Deploy Book

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pages:
    name: GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Build mdBook
        run: mdbook build

      - name: Generate sitemap
        run: |
          cd book
          npx static-sitemap-cli --base https://rust-tieng-viet.github.io
          cat sitemap.xml

      - name: Comment
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: Build book successfully!
          reactions: tada
          comment_includes: Build book
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Deploy to GitHub
        if: ${{ github.event_name == 'push'}}
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: book

