name: Deploy Book

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  book:
    name: Build mdBook and Deploy 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: latest

      - name: Build mdBook
        run: mdbook build

      - name: Generate sitemap
        run: |
          cd book
          npx static-sitemap-cli --base https://${{ github.event.repository.name }}.github.io
          cat sitemap.xml

      - name: Comment PR
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: Build book successfully!
          reactions: tada
          comment_includes: Build book
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Deploy to GitHub
        if: github.event_name == 'push'
        id: deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: book

      - name: Comment Commit
        if: github.event_name == 'push' && steps.deploy.outputs.deployment-status == 'success'
        uses: peter-evans/commit-comment@v2
        with:
          body: Deploy successfully https://${{ github.event.repository.name }}.github.io!
          token: ${{ secrets.BOT_TOKEN }}
