name: Deploy Book

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened

jobs:
  pages:
    name: GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          
      - uses: Swatinem/rust-cache@v1

      - name: Install mdBook
        run: (test -x $HOME/.cargo/bin/mdbook || cargo install mdbook --no-default-features --features search)

      - name: Build mdBook
        run: mdbook build

      - name: Generate sitemap
        run: |
          cd book
          npx static-sitemap-cli --base https://rust-tieng-viet.github.io
          cat sitemap.xml

      - name: Comment
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Build book successfully!
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub
        if: ${{ github.event_name == 'push'}}
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: book

